### ISSUE TITLE
Clarify linear regression question 6 in pre-work notebook

### ISSUE THREAD

**Issue by roxana-pamfil-qb** [fonnesbeck/Bayes_Computing_Course#4]
It is not entirely clear what to calculate for the following question:

> 6. What is the log probability that all the weights are 0, and all the targets are 1, given your generated features?

In particular, are we accounting for the targets that we generated in step 4? So to get the log probability that all the weights are 0, are we sampling from the prior P(weights) or from the posterior P(weights | features, targets)?

**Comment by ColCarroll** [comment]
Thanks for the question!

We are _not_ accounting for the targets that we generated in step 4. The goal is to get used to thinking of these models as joint probability distributions, since that is how we will be using them for MCMC.

That's a pretty high level answer, though. Here is one way to start this problem that might be more clear:

```python
example_weights = np.zeros(...)
logp_weights = st.normal(...).logpdf(example_weights)

example_targets = np.ones(...)
logp_targets = ...

total_logp = ...
```

**Comment by roxana-pamfil-qb** [comment]
Thanks! Yes, that's how I originally answered the question, but I wasn't sure.
